# Python Modules

## 2. Pandas

In [577]:
## What is Pandas?

# Pandas is a Python library used for working with data

#It helps you:
#        Read data
#        Analyze data
#        Clean data
#        Modify data
#        Save data

In [ ]:
## Why Use Pandas?

## Without Pandas

# Imagine finding:

# Average salary
# Highest marks
# Students older than 20

## Using normal Python would require many loops

## With Pandas -> Much easier

df["marks"].mean()
df["marks"].max()
df[df["Age"]>20]

### Install Pandas

In [ ]:
%pip install pandas

Requirement already satisfied: pandas in c:\Users\DELL\AppData\Local\Programs\Python\Python313\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in c:\Users\DELL\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.1.0)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\DELL\AppData\Roaming\Python\Python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\DELL\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\DELL\AppData\Roaming\Python\Python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

### Import Pandas

In [ ]:
import pandas as pd

## Why pd? -> Just a shortcut

## Instead of writing -> pandas.DataFrame()
pandas.DataFrame()

## we write -> pd.DataFrame()
pd.DataFrame()

### Check Version

In [ ]:
import pandas as pd

print(pd.__version__)

3.0.3

### Series

In [ ]:
# A Series is one column -> only one column

# Series – A one-dimensional labeled array
import pandas as pd

s = pd.Series([10, 20, 30])
print(s)

## In Output -> 0,1,2 are indexes

0    10
1    20
2    30
dtype: int64

### Access Value

In [ ]:
s = pd.Series([10, 20, 30])
print(s[0])

10

### Custom Index

In [ ]:
## Custom Index

# Instead of numbers, -> give names

a = [12,23,45]
s = pd.Series(a,index=["A","B","C"])
print(s)

A    12
B    23
C    45
dtype: int64

### Access

In [ ]:
print(s["B"])

23

### Series from Dictionary

In [ ]:
## Dictionary

marks = {
    "Ali" : 90,
    "Alisha" : 100
}

## Convert to Series

s = pd.Series(marks)
print(s)

# Dictionary keys become indexes

Ali        90
Alisha    100
dtype: int64
Ali    90
dtype: int64

In [ ]:
## Select Specific Keys

s1 = pd.Series(marks,index=["Ali"])
print(s1)

Ali    90
dtype: int64

## DataFrame

In [ ]:
# DataFrame – A two-dimensional table with rows and columns
## A DataFrame is a complete table

import pandas as pd

## Create DataFrame
data = {
    "Name": ["Alisha", "Ali", "Zarmeen"],
    "Age": [25, 30, 20],
    "City": ["Lahore", "Sahiwal", "Multan"]
}

df = pd.DataFrame(data)
print(df)

      Name  Age     City
0   Alisha   25   Lahore
1      Ali   30  Sahiwal
2  Zarmeen   20   Multan

### DataFrame from Dictionary

In [ ]:
## DataFrame from Dictionary

data = {
    "Calories" : [420,340,201],
    "Duration": [40,50,45]
}

df = pd.DataFrame(data)
print(df)

## Each key becomes a column

   Calories  Duration
0       420        40
1       340        50
2       201        45

### loc[]

In [ ]:
## loc[]

## Used to access rows

print(df.loc[0]) # one row in output

Calories    420
Duration     40
Name: 0, dtype: int64
Calories    201
Duration     45
Name: 2, dtype: int64

In [ ]:
## Multiple Rows

print(df.loc[[0,1]])

## Notice the double brackets [[ ]] because ->  passing a list of row indexes

   Calories  Duration
0       420        40
1       340        50

### Named Index

In [ ]:
data = {
    "Calories" : [420,340,201],
    "Duration": [40,50,45]
}

df = pd.DataFrame(data,index=["day1","day2","day3"])
print(df)

      Calories  Duration
day1       420        40
day2       340        50
day3       201        45

### Access

In [ ]:
print(df.loc["day2"])

Calories    340
Duration     50
Name: day2, dtype: int64

## Read CSV

In [579]:
## Read CSV

# CSV = Comma Separated Values

## Load 
df = pd.read_csv("students.csv")

## Now the CSV becomes a DataFrame

#Print
print(df)

   Student_ID     Name   Age  Gender               Department  Semester  CGPA  \
0         101   Tayyab  20.0    Male         Computer Science         4  3.45
1         102     Zari  21.0  Female     Software Engineering         5  3.80
2         103    Ahmed   NaN    Male         Computer Science         4  2.95
3         104  Ibrahim  22.0  Female             Data Science         6  3.65
4         105   Kainat  20.0    Male         Computer Science         4   NaN
5         106   Sajjad  21.0  Female     Software Engineering         5  3.90
6         107  Unknown  23.0    Male  Artificial Intelligence         7  2.80
7         108     DevX  20.0  Female         Computer Science         4  3.50
8         109      NaN  22.0  Female  Artificial Intelligence         6  3.10
9         110    Ahmed  21.0    Male     Software Engineering         5  3.20

         City  Attendance  Marks
0      Lahore        90.0   85.0
1     Karachi        95.0   91.0
2   Islamabad        88.0   76.0
3      Lahore         NaN   89.0
4  Faisalabad        82.0   72.0
5     Karachi        97.0    NaN
6      Multan        70.0    NaN
7      Lahore        91.0   87.0
8   Islamabad        85.0   80.0
9      Lahore        89.0   78.0

In [602]:
## Entire Table

print(df.to_string())

## Without to_string(), Pandas may show only the first and last few rows for large datasets

   Student_ID     Name        Age  Gender               Department  Semester  CGPA        City  Attendance  Marks
0         101   Tayyab  20.000000    Male         Computer Science         4  3.45      Lahore        90.0   85.0
1         102     Zari  21.000000  Female     Software Engineering         5  3.80     Karachi        95.0   91.0
2         103    Ahmed  21.111111    Male         Computer Science         4  2.95   Islamabad        88.0   76.0
3         104  Ibrahim  22.000000  Female             Data Science         6  3.65      Lahore         NaN   89.0
4         105   Kainat  20.000000    Male         Computer Science         4   NaN  Faisalabad        82.0   72.0
5         106   Sajjad  21.000000  Female     Software Engineering         5  3.90     Karachi        97.0    NaN
6         107  Unknown  23.000000    Male  Artificial Intelligence         7  2.80      Multan        70.0    NaN
7         108     DevX  20.000000  Female         Computer Science         4  3.50      Lahore        91.0   87.0
8         109      NaN  22.000000  Female  Artificial Intelligence         6  3.10   Islamabad        85.0   80.0
9         110    Ahmed  21.000000    Male     Software Engineering         5  3.20      Lahore        89.0   78.0

## Read JSON

In [603]:
## Read JSON

# JSON

{
    "name" : "Alisha",
    "age" : 21
}

## Read

df = pd.read_json("students.json")
print(df)

     name  age
0     Ali   20
1  Alisha   22
2  Sajjad   21

In [604]:
## or directly from a dictionary

students = {
"Name":["Ali","ALisha"],
"Age":[20,21]
}

df = pd.DataFrame(students)
print(df)

     Name  Age
0     Ali   20
1  ALisha   21

##  Common Pandas Operations

In [605]:
# Read Dataset

import pandas as pd

df = pd.read_csv("students.csv")
print(df)

   Student_ID     Name   Age  Gender               Department  Semester  CGPA  \
0         101   Tayyab  20.0    Male         Computer Science         4  3.45
1         102     Zari  21.0  Female     Software Engineering         5  3.80
2         103    Ahmed   NaN    Male         Computer Science         4  2.95
3         104  Ibrahim  22.0  Female             Data Science         6  3.65
4         105   Kainat  20.0    Male         Computer Science         4   NaN
5         106   Sajjad  21.0  Female     Software Engineering         5  3.90
6         107  Unknown  23.0    Male  Artificial Intelligence         7  2.80
7         108     DevX  20.0  Female         Computer Science         4  3.50
8         109      NaN  22.0  Female  Artificial Intelligence         6  3.10
9         110    Ahmed  21.0    Male     Software Engineering         5  3.20

         City  Attendance  Marks
0      Lahore        90.0   85.0
1     Karachi        95.0   91.0
2   Islamabad        88.0   76.0
3      Lahore         NaN   89.0
4  Faisalabad        82.0   72.0
5     Karachi        97.0    NaN
6      Multan        70.0    NaN
7      Lahore        91.0   87.0
8   Islamabad        85.0   80.0
9      Lahore        89.0   78.0

## Pandas - Analyzing DataFrames

### head()

In [606]:
## Shows first rows
#Default First 5 rows
df.head()

,Student_ID,Name,Age,Gender,Department,Semester,CGPA,City,Attendance,Marks
0,101,Tayyab,20.0,Male,Computer Science,4,3.45,Lahore,90.0,85.0
1,102,Zari,21.0,Female,Software Engineering,5,3.80,Karachi,95.0,91.0
2,103,Ahmed,NaN,Male,Computer Science,4,2.95,Islamabad,88.0,76.0
3,104,Ibrahim,22.0,Female,Data Science,6,3.65,Lahore,NaN,89.0
4,105,Kainat,20.0,Male,Computer Science,4,NaN,Faisalabad,82.0,72.0

### Specific rows

In [607]:
#First 10 rows
df.head(10)

,Student_ID,Name,Age,Gender,Department,Semester,CGPA,City,Attendance,Marks
0,101,Tayyab,20.0,Male,Computer Science,4,3.45,Lahore,90.0,85.0
1,102,Zari,21.0,Female,Software Engineering,5,3.80,Karachi,95.0,91.0
2,103,Ahmed,NaN,Male,Computer Science,4,2.95,Islamabad,88.0,76.0
3,104,Ibrahim,22.0,Female,Data Science,6,3.65,Lahore,NaN,89.0
4,105,Kainat,20.0,Male,Computer Science,4,NaN,Faisalabad,82.0,72.0
5,106,Sajjad,21.0,Female,Software Engineering,5,3.90,Karachi,97.0,NaN
6,107,Unknown,23.0,Male,Artificial Intelligence,7,2.80,Multan,70.0,NaN
7,108,DevX,20.0,Female,Computer Science,4,3.50,Lahore,91.0,87.0
8,109,NaN,22.0,Female,Artificial Intelligence,6,3.10,Islamabad,85.0,80.0
9,110,Ahmed,21.0,Male,Software Engineering,5,3.20,Lahore,89.0,78.0

### tail()

In [608]:
#Shows Last Rows
df.tail()
## Default last 5 rows

,Student_ID,Name,Age,Gender,Department,Semester,CGPA,City,Attendance,Marks
5,106,Sajjad,21.0,Female,Software Engineering,5,3.9,Karachi,97.0,NaN
6,107,Unknown,23.0,Male,Artificial Intelligence,7,2.8,Multan,70.0,NaN
7,108,DevX,20.0,Female,Computer Science,4,3.5,Lahore,91.0,87.0
8,109,NaN,22.0,Female,Artificial Intelligence,6,3.1,Islamabad,85.0,80.0
9,110,Ahmed,21.0,Male,Software Engineering,5,3.2,Lahore,89.0,78.0

### info()

In [609]:
# Dataset Information
df.info()

## It tells:
# -> Number of rows
# -> Number of columns
# -> Column names
# -> Data types
# -> Null values
# -> Memory usage

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Student_ID  10 non-null     int64
 1   Name        9 non-null      str
 2   Age         9 non-null      float64
 3   Gender      10 non-null     str
 4   Department  10 non-null     str
 5   Semester    10 non-null     int64
 6   CGPA        9 non-null      float64
 7   City        10 non-null     str
 8   Attendance  9 non-null      float64
 9   Marks       8 non-null      float64
dtypes: float64(4), int64(2), str(4)
memory usage: 932.0 bytes

In [610]:
#Shape
df.shape

(10, 10)

In [611]:
#Columns
df.columns

Index(['Student_ID', 'Name', 'Age', 'Gender', 'Department', 'Semester', 'CGPA',
       'City', 'Attendance', 'Marks'],
      dtype='str')

In [612]:
# Data Types
df.dtypes

Student_ID      int64
Name              str
Age           float64
Gender            str
Department        str
Semester        int64
CGPA          float64
City              str
Attendance    float64
Marks         float64
dtype: object

In [613]:
# Statistical Summary
df.describe()

       Student_ID        Age   Semester      CGPA  Attendance     Marks
count    10.00000   9.000000  10.000000  9.000000    9.000000   8.00000
mean    105.50000  21.111111   5.000000  3.372222   87.444444  82.25000
std       3.02765   1.054093   1.054093  0.382517    7.986099   6.75595
min     101.00000  20.000000   4.000000  2.800000   70.000000  72.00000
25%     103.25000  20.000000   4.000000  3.100000   85.000000  77.50000
50%     105.50000  21.000000   5.000000  3.450000   89.000000  82.50000
75%     107.75000  22.000000   5.750000  3.650000   91.000000  87.50000
max     110.00000  23.000000   7.000000  3.900000   97.000000  91.00000

## Null Values

In [614]:
## Null Values 

# NULL -> means -> No data

## Example

#Name	  Marks
# Ali	   90
# Ahmed	   NULL
# Alisha   80

## Ahmed's marks are missing

# Pandas shows this in info() so -> know the dataset may need cleaning

## Data Cleaning

In [615]:
# Missing Values
df.isnull()

,Student_ID,Name,Age,Gender,Department,Semester,CGPA,City,Attendance,Marks
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,True,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,True,False
4,False,False,False,False,False,False,True,False,False,False
5,False,False,False,False,False,False,False,False,False,True
6,False,False,False,False,False,False,False,False,False,True
7,False,False,False,False,False,False,False,False,False,False
8,False,True,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False

In [616]:
df.isnull().sum()

Student_ID    0
Name          1
Age           1
Gender        0
Department    0
Semester      0
CGPA          1
City          0
Attendance    1
Marks         2
dtype: int64

In [617]:
#FIll Missing Values
df["Age"] = df["Age"].fillna(df["Age"].mean())

In [618]:
df.isnull().sum()

Student_ID    0
Name          1
Age           0
Gender        0
Department    0
Semester      0
CGPA          1
City          0
Attendance    1
Marks         2
dtype: int64

In [619]:
print(df)

   Student_ID     Name        Age  Gender               Department  Semester  \
0         101   Tayyab  20.000000    Male         Computer Science         4
1         102     Zari  21.000000  Female     Software Engineering         5
2         103    Ahmed  21.111111    Male         Computer Science         4
3         104  Ibrahim  22.000000  Female             Data Science         6
4         105   Kainat  20.000000    Male         Computer Science         4
5         106   Sajjad  21.000000  Female     Software Engineering         5
6         107  Unknown  23.000000    Male  Artificial Intelligence         7
7         108     DevX  20.000000  Female         Computer Science         4
8         109      NaN  22.000000  Female  Artificial Intelligence         6
9         110    Ahmed  21.000000    Male     Software Engineering         5

   CGPA        City  Attendance  Marks
0  3.45      Lahore        90.0   85.0
1  3.80     Karachi        95.0   91.0
2  2.95   Islamabad        88.0   76.0
3  3.65      Lahore         NaN   89.0
4   NaN  Faisalabad        82.0   72.0
5  3.90     Karachi        97.0    NaN
6  2.80      Multan        70.0    NaN
7  3.50      Lahore        91.0   87.0
8  3.10   Islamabad        85.0   80.0
9  3.20      Lahore        89.0   78.0

In [620]:
#Selecting Data
df["Name"]

0     Tayyab
1       Zari
2      Ahmed
3    Ibrahim
4     Kainat
5     Sajjad
6    Unknown
7       DevX
8        NaN
9      Ahmed
Name: Name, dtype: str

In [621]:
df[["Name", "CGPA"]]

      Name  CGPA
0   Tayyab  3.45
1     Zari  3.80
2    Ahmed  2.95
3  Ibrahim  3.65
4   Kainat   NaN
5   Sajjad  3.90
6  Unknown  2.80
7     DevX  3.50
8      NaN  3.10
9    Ahmed  3.20

In [622]:
df[df["CGPA"] > 3.5]

,Student_ID,Name,Age,Gender,Department,Semester,CGPA,City,Attendance,Marks
1,102,Zari,21.0,Female,Software Engineering,5,3.80,Karachi,95.0,91.0
3,104,Ibrahim,22.0,Female,Data Science,6,3.65,Lahore,NaN,89.0
5,106,Sajjad,21.0,Female,Software Engineering,5,3.90,Karachi,97.0,NaN

In [623]:
#Concept	            Meaning

# Pandas	        Python library for data analysis
# Series	        One-dimensional column
# DataFrame	        Two-dimensional table
# pd.Series()	    Create a Series
# pd.DataFrame()	Create a DataFrame
# loc[]	            Access rows by label/index
# read_csv()	    Read a CSV file
# read_json()	    Read a JSON file
# head()	        First 5 rows
# tail()	        Last 5 rows
# info()	        Dataset summary (rows, columns, types, null values)
# to_string()	    Print the complete DataFrame